export const _nodes = [
	{
		id: '_0',
		type: 'labeled-group',
		position: { x: -188, y: -408 },
		style: {
			height: 110,
			backgroundColor: '#d9d4d4',
			color: '#000',
			width: 629,
		},
		data: { label: '' },
		measured: { width: 1616, height: 762 },
		width: 1616,
		height: 762,
		resizing: false,
		selected: false,
		dragging: false,
	},
	{
		id: 'Customer_b3dzi6',
		type: 'labeled-group',
		position: { x: 0, y: 0 },
		style: {
			height: 90,
			backgroundColor: 'rgba(255, 255, 255, 0)',
			color: '#bfb715',
			width: 429,
		},
		data: { label: 'Customer' },
		measured: { width: 1616, height: 80 },
		selected: false,
		dragging: false,
		parentId: '_0',
		extent: 'parent',
		width: 1616,
		height: 80,
		resizing: false,
	},
	{
		id: 'SIA (incl. TSP, MMD)_cailbd',
		type: 'custom-node',
		position: { x: 105, y: 0 },
		style: { backgroundColor: '#fff7ab', color: '#000' },
		measured: { height: 80, width: 129 },
		data: { label: 'SIA (incl. TSP, MMD)' },
		extent: 'parent',
		parentId: 'Customer_b3dzi6',
		selected: false,
		dragging: false,
		width: 129,
		height: 80,
		resizing: false,
	},
	{
		id: 'TSP, MMD, EC Purchasing update the DSS, Production team gets status frim DSS_5u15sw',
		type: 'custom-node',
		position: { x: 744, y: 0 },
		style: {
			backgroundColor: 'rgba(235, 235, 235, 0)',
			color: '#000000',
		},
		measured: { height: 69, width: 192 },
		data: {
			label: 'TSP, MMD, EC Purchasing update the DSS, Production team gets status frim DSS',
		},
		extent: 'parent',
		parentId: 'Customer_b3dzi6',
		selected: false,
		dragging: false,
		width: 192,
		height: 69,
		resizing: false,
	},
	{
		id: 'Planning_vzgqyl',
		type: 'labeled-group',
		position: { x: 0, y: 80 },
		style: { height: 90, backgroundColor: '#ffffff', color: '#0027b3' },
		data: { label: 'Planning' },
		measured: { width: 1616, height: 90 },
		resizing: false,
		selected: false,
		parentId: '_0',
		extent: 'parent',
		dragging: false,
		width: 1616,
		height: 90,
	},
	{
		id: 'Standards team_zhj1fr',
		type: 'custom-node',
		position: { x: 104, y: 0 },
		data: { label: 'Standards team' },
		extent: 'parent',
		parentId: 'Planning_vzgqyl',
		measured: { width: 129, height: 90 },
		selected: false,
		dragging: false,
		style: { backgroundColor: '#0028c7', color: '#ffffff' },
		width: 129,
		height: 90,
		resizing: false,
	},
	{
		id: 'Establish workflow, critical path and items via input meeting_uiqw3u',
		type: 'custom-node',
		position: { x: 260, y: 0 },
		data: {
			label: 'Establish workflow, critical path and items via input meeting',
			shape: 'ellipse',
		},
		extent: 'parent',
		parentId: 'Planning_vzgqyl',
		measured: { width: 154, height: 90 },
		selected: false,
		dragging: false,
		style: { backgroundColor: '#ffe787', color: '#000' },
		width: 154,
		height: 90,
		resizing: false,
	},
	{
		id: 'Check availability of toos, liaise with toolstore_oo6wq1',
		type: 'custom-node',
		position: { x: 464, y: 0 },
		data: {
			label: 'Check availability of toos, liaise with toolstore',
			shape: 'ellipse',
		},
		extent: 'parent',
		parentId: 'Planning_vzgqyl',
		measured: { width: 154, height: 90 },
		selected: false,
		style: { backgroundColor: '#fff6a6', color: '#000' },
		width: 154,
		height: 90,
		resizing: false,
		dragging: false,
	},
	{
		id: 'Ops_1pci',
		type: 'labeled-group',
		position: { x: 0, y: 168 },
		style: {
			height: 90,
			backgroundColor: 'rgba(255, 255, 255, 0)',
			color: '#000',
		},
		data: { label: 'Ops' },
		measured: { width: 1616, height: 594 },
		selected: false,
		parentId: '_0',
		extent: 'parent',
		dragging: false,
		width: 1616,
		height: 594,
		resizing: false,
	},
	{
		id: 'OM/SFM.AFM_m70s8t',
		type: 'labeled-group',
		position: { x: 104, y: 4 },
		style: {
			height: 90,
			backgroundColor: 'rgba(255, 255, 255, 0)',
			color: '#000',
		},
		data: { label: 'OM/SFM.AFM' },
		measured: { width: 1512, height: 138 },
		selected: false,
		parentId: 'Ops_1pci',
		extent: 'parent',
		dragging: false,
		width: 1512,
		height: 138,
		resizing: false,
	},
	{
		id: 'Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706',
		type: 'custom-node',
		position: { x: 336, y: 0 },
		data: {
			label:
				'Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues',
		},
		extent: 'parent',
		parentId: 'OM/SFM.AFM_m70s8t',
		measured: { width: 927, height: 38 },
		selected: false,
		dragging: false,
		width: 927,
		height: 38,
		resizing: false,
	},
	{
		id: 'AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz',
		type: 'custom-node',
		position: { x: 632, y: 44 },
		data: {
			label: 'AFM: arrange the operational induction tasks (parking aircraft, timing of induction)',
		},
		extent: 'parent',
		parentId: 'OM/SFM.AFM_m70s8t',
		measured: { width: 630, height: 38 },
		selected: false,
		dragging: false,
		width: 630,
		height: 38,
		resizing: false,
	},
	{
		id: 'SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n',
		type: 'custom-node',
		position: { x: 632, y: 92 },
		data: { label: 'SFM/OM/AFM: Manage data-to-day manpower delegation' },
		extent: 'parent',
		parentId: 'OM/SFM.AFM_m70s8t',
		measured: { width: 629, height: 38 },
		selected: false,
		dragging: false,
		width: 629,
		height: 38,
		resizing: false,
	},
	{
		id: 'BM Ops Line_qcjl07',
		type: 'labeled-group',
		position: { x: 104, y: 144 },
		style: {
			height: 90,
			backgroundColor: 'rgba(255, 255, 255, 0)',
			color: '#000',
		},
		data: { label: 'BM Ops Line' },
		measured: { width: 1512, height: 90 },
		selected: true,
		parentId: 'Ops_1pci',
		extent: 'parent',
		dragging: false,
		width: 1512,
		height: 90,
		resizing: false,
	},
	{
		id: 'Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s',
		type: 'custom-node',
		position: { x: 632, y: 12 },
		data: {
			label:
				'Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify',
		},
		extent: 'parent',
		parentId: 'BM Ops Line_qcjl07',
		measured: { width: 266, height: 66 },
		selected: false,
		dragging: false,
		resizing: false,
		width: 266,
		height: 66,
	},
	{
		id: 'Bay Planners_atkxw9',
		type: 'labeled-group',
		position: { x: 104, y: 240 },
		style: {
			height: 90,
			backgroundColor: 'rgba(255, 255, 255, 0)',
			color: '#000',
		},
		data: { label: 'Bay Planners' },
		measured: { width: 1512, height: 74 },
		selected: false,
		dragging: false,
		parentId: 'Ops_1pci',
		extent: 'parent',
		width: 1512,
		height: 74,
		resizing: false,
	},
	{
		id: 'Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4',
		type: 'custom-node',
		position: { x: 332, y: 4 },
		data: {
			label: 'Collectedprinted planned tskcards and distrubute onto A-frame boards',
		},
		extent: 'parent',
		parentId: 'Bay Planners_atkxw9',
		measured: { width: 130, height: 66 },
		selected: false,
		dragging: false,
		width: 130,
		height: 66,
		resizing: false,
	},
	{
		id: 'Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo',
		type: 'custom-node',
		position: { x: 872, y: 12 },
		data: {
			label: 'Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required',
		},
		extent: 'parent',
		parentId: 'Bay Planners_atkxw9',
		measured: { width: 294, height: 38 },
		selected: false,
		dragging: false,
		width: 294,
		height: 38,
		resizing: false,
	},
	{
		id: 'Project Engineers_ccw80z',
		type: 'labeled-group',
		position: { x: 104, y: 320 },
		style: {
			height: 90,
			backgroundColor: 'rgba(255, 255, 255, 0)',
			color: '#000',
		},
		data: { label: 'Project Engineers' },
		measured: { width: 1512, height: 90 },
		selected: false,
		parentId: 'Ops_1pci',
		extent: 'parent',
		dragging: false,
		width: 1512,
		height: 90,
		resizing: false,
	},
	{
		id: 'BM Toolstore_mvutf0',
		type: 'labeled-group',
		position: { x: 104, y: 420 },
		style: {
			height: 90,
			backgroundColor: 'rgba(255, 255, 255, 0)',
			color: '#000',
		},
		data: { label: 'BM Toolstore' },
		measured: { width: 1512, height: 90 },
		selected: false,
		parentId: 'Ops_1pci',
		extent: 'parent',
		dragging: false,
		width: 1512,
		height: 90,
		resizing: false,
	},
	{
		id: 'BM Kitting_fahx69',
		type: 'labeled-group',
		position: { x: 104, y: 520 },
		style: {
			height: 90,
			backgroundColor: 'rgba(255, 255, 255, 0)',
			color: '#000',
		},
		data: { label: 'BM Kitting' },
		measured: { width: 1512, height: 74 },
		selected: false,
		parentId: 'Ops_1pci',
		extent: 'parent',
		dragging: false,
		width: 1512,
		height: 74,
		resizing: false,
	},
	{
		id: 'Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p',
		type: 'custom-node',
		position: { x: 328, y: 0 },
		data: {
			label:
				'Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners',
		},
		extent: 'parent',
		parentId: 'BM Kitting_fahx69',
		measured: { width: 175, height: 74 },
		selected: false,
		dragging: false,
		width: 175,
		height: 74,
		resizing: false,
	},
	{
		id: 'Final_14ez4m',
		type: 'custom-node',
		position: { x: 1453, y: 328 },
		data: { label: 'Final', shape: 'ellipse' },
		extent: 'parent',
		parentId: '_0',
		measured: { width: 40, height: 38 },
		selected: false,
		dragging: false,
		style: { backgroundColor: '#ccb800', color: '#ffffff' },
		width: 40,
		height: 38,
		resizing: false,
	},
];

export const _edges = [
	{
		type: 'customEdge',
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'Establish workflow, critical path and items via input meeting_uiqw3u',
		sourceHandle: '-right_Establish workflow, critical path and items via input meeting_uiqw3u',
		target: 'Check availability of toos, liaise with toolstore_oo6wq1',
		targetHandle: '-left_Check availability of toos, liaise with toolstore_oo6wq1',
		id: 'xy-edge__Establish workflow, critical path and items via input meeting_uiqw3u-right_Establish workflow, critical path and items via input meeting_uiqw3u-Check availability of toos, liaise with toolstore_oo6wq1-left_Check availability of toos, liaise with toolstore_oo6wq1',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'Establish workflow, critical path and items via input meeting_uiqw3u',
		sourceHandle: '-bottom_Establish workflow, critical path and items via input meeting_uiqw3u',
		target:
			'Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706',
		targetHandle:
			'-left_Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706',
		type: 'customEdge',
		id: 'xy-edge__Establish workflow, critical path and items via input meeting_uiqw3u-bottom_Establish workflow, critical path and items via input meeting_uiqw3u-Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706-left_Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'Establish workflow, critical path and items via input meeting_uiqw3u',
		sourceHandle: '-bottom_Establish workflow, critical path and items via input meeting_uiqw3u',
		target: 'AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz',
		targetHandle: '-left_AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz',
		type: 'customEdge',
		id: 'xy-edge__Establish workflow, critical path and items via input meeting_uiqw3u-bottom_Establish workflow, critical path and items via input meeting_uiqw3u-AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz-left_AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'Establish workflow, critical path and items via input meeting_uiqw3u',
		sourceHandle: '-bottom_Establish workflow, critical path and items via input meeting_uiqw3u',
		target: 'SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n',
		targetHandle: '-left_SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n',
		type: 'customEdge',
		id: 'xy-edge__Establish workflow, critical path and items via input meeting_uiqw3u-bottom_Establish workflow, critical path and items via input meeting_uiqw3u-SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n-left_SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'Establish workflow, critical path and items via input meeting_uiqw3u',
		sourceHandle: '-bottom_Establish workflow, critical path and items via input meeting_uiqw3u',
		target: 'Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4',
		targetHandle: '-left_Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4',
		type: 'customEdge',
		id: 'xy-edge__Establish workflow, critical path and items via input meeting_uiqw3u-bottom_Establish workflow, critical path and items via input meeting_uiqw3u-Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4-left_Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4',
		label: 'Gant chart, Masterlist, check package (by trade and respactive areas), DSS on xls',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4',
		sourceHandle: '-right_Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4',
		target:
			'Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s',
		targetHandle:
			'-left_Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s',
		type: 'customEdge',
		id: 'xy-edge__Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4-right_Collectedprinted planned tskcards and distrubute onto A-frame boards_8yh3h4-Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s-left_Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source:
			'Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s',
		sourceHandle:
			'-right_Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s',
		target: 'Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo',
		targetHandle: '-left_Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo',
		type: 'customEdge',
		id: 'xy-edge__Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s-right_Check for anu discreapancies in task cards (throughtout the check); any issues to be hightlighted to TSP to rectify_nj8f8s-Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo-left_Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'Establish workflow, critical path and items via input meeting_uiqw3u',
		sourceHandle: '-bottom_Establish workflow, critical path and items via input meeting_uiqw3u',
		target:
			'Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p',
		targetHandle:
			'-left_Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p',
		type: 'customEdge',
		id: 'xy-edge__Establish workflow, critical path and items via input meeting_uiqw3u-bottom_Establish workflow, critical path and items via input meeting_uiqw3u-Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p-left_Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source:
			'Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p',
		sourceHandle:
			'-right_Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p',
		target: 'TSP, MMD, EC Purchasing update the DSS, Production team gets status frim DSS_5u15sw',
		targetHandle: '-left_TSP, MMD, EC Purchasing update the DSS, Production team gets status frim DSS_5u15sw',
		type: 'customEdge',
		id: 'xy-edge__Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p-right_Collect  and inspect pre-load and kittig itens against the pre-load list, working together with Bay Palnners_bfl35p-TSP, MMD, EC Purchasing update the DSS, Production team gets status frim DSS_5u15sw-left_TSP, MMD, EC Purchasing update the DSS, Production team gets status frim DSS_5u15sw',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo',
		sourceHandle: '-right_Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo',
		target: 'Final_14ez4m',
		targetHandle: '-left_Final_14ez4m',
		type: 'customEdge',
		id: 'xy-edge__Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo-right_Tranfer defects in Defect Log to Supplementary Job Cards, Plan for work required_qp3plo-Final_14ez4m-left_Final_14ez4m',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n',
		sourceHandle: '-right_SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n',
		target: 'Final_14ez4m',
		targetHandle: '-left_Final_14ez4m',
		type: 'customEdge',
		id: 'xy-edge__SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n-right_SFM/OM/AFM: Manage data-to-day manpower delegation_sui02n-Final_14ez4m-left_Final_14ez4m',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source: 'AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz',
		sourceHandle: '-right_AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz',
		target: 'Final_14ez4m',
		targetHandle: '-left_Final_14ez4m',
		type: 'customEdge',
		id: 'xy-edge__AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz-right_AFM: arrange the operational induction tasks (parking aircraft, timing of induction)_tiwmmz-Final_14ez4m-left_Final_14ez4m',
	},
	{
		markerEnd: { type: 'arrowclosed', color: '#000' },
		style: { strokeWidth: 2, stroke: '#000' },
		source:
			'Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706',
		sourceHandle:
			'-right_Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706',
		target: 'Final_14ez4m',
		targetHandle: '-left_Final_14ez4m',
		type: 'customEdge',
		id: 'xy-edge__Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706-right_Start production meeting & progress meeting cadence - forum to duscuss critital pathm cincurency, next steops, resolve issues_rlj706-Final_14ez4m-left_Final_14ez4m',
	},
];
